version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: '14:00'
  - ignore:
    - dependency-name: org.hibernate.validator
      versions:
        - ">=7.0.0"
  commit-message:
    prefix: "chore"
    include: "scope"
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: '14:00'
  commit-message:
    prefix: "chore"
    include: "scope"
  open-pull-requests-limit: 10